Resources:
  PortfolioTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "symbol"
          "AttributeType": "S"
        - "AttributeName": "stockId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "symbol"
          "KeyType": "HASH"
        - "AttributeName": "stockId"
          "KeyType": "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Portfolio"